version: '3.5'

services:

 web_dev:
  build: ./app
  ports:
   - "5000:5000"
  volumes:
   - ./app:/app
  environment:
   - DB=mongodb://mongodb:27017

 mongodb:
  image: mongo:4.0
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet

networks:
 default:
  name: web_dev